name: photo_manager
description: A Flutter plugin that provides assets abstraction management APIs on Android, iOS, and macOS.
repository: https://github.com/fluttercandies/flutter_photo_manager
version: 3.0.1-dev.4

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager_image_provider: ^2.1.0
dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercandies.photo_manager
        pluginClass: PhotoManagerPlugin
      ios:
        pluginClass: PhotoManagerPlugin
      macos:
        pluginClass: PhotoManagerPlugin
